### ISSUE TITLE
move slide number to top left, bump up controls

### ISSUE THREAD

**Issue by tamouse** [gdiminneapolis/jekyll-reveal-starter-kit#8]
In overrides:

``` scss
.reveal {
   .controls {
    bottom: 20px;
  }
  .slide-number {
    top: 15px;
    right: inherit;
    bottom: inherit;
    left: 15px;
    font-size: 15px;
  }
}
```
